/* lang.js — BuildOrder.ai i18n (EN / ES) */
(function () {
  var TR = {
    en: {
      /* nav */
      'nav.back': '← Dashboard',

      /* common buttons */
      'btn.copy': 'Copy',
      'btn.download': 'Download .txt',
      'btn.try_again': 'Try Again',
      'btn.saving': 'Saving…',

      /* status */
      'status.draft': 'draft',
      'status.sent': 'sent',
      'status.paid': 'paid',
      'status.signed': 'signed',
      'status.complete': 'complete',
      'status.accepted': 'accepted',

      /* dashboard */
      'dash.tools': 'Document Tools',
      'dash.recent': 'Recent Documents',
      'dash.filter.all': 'All',
      'dash.filter.contracts': 'Contracts',
      'dash.filter.estimates': 'Estimates',
      'dash.filter.invoices': 'Invoices',
      'dash.filter.change_orders': 'Change Orders',
      'dash.filter.subcontractors': 'Subcontractors',
      'dash.filter.lien_waivers': 'Lien Waivers',
      'dash.filter.takeoffs': 'Takeoffs',
      'dash.stat.total': 'Total Docs',
      'dash.stat.contracts': 'Contracts',
      'dash.stat.invoices': 'Invoices',
      'dash.stat.outstanding': 'Outstanding',
      'dash.empty': 'No documents yet',
      'dash.empty.sub': 'Pick a tool above to create your first document.',
      'dash.new': 'New',

      /* tool names */
      'tool.contract': 'Contract Generator',
      'tool.contract.desc': 'State-specific residential & commercial contracts',
      'tool.estimate': 'Estimate Generator',
      'tool.estimate.desc': 'Professional itemized project estimates',
      'tool.invoice': 'Invoice Generator',
      'tool.invoice.desc': 'Payment-ready invoices with line items',
      'tool.change_order': 'Change Order',
      'tool.change_order.desc': 'Document scope changes & price adjustments',
      'tool.subcontractor': 'Subcontractor Agreement',
      'tool.subcontractor.desc': 'Full sub agreements with insurance requirements',
      'tool.lien_waiver': 'Lien Waiver',
      'tool.lien_waiver.desc': 'All 4 waiver types — conditional & unconditional',
      'tool.takeoff': 'Material Takeoff',
      'tool.takeoff.desc': 'Materials list with quantities & cost estimates',
      'tool.photos': 'Job Photo Log',
      'tool.photos.desc': 'Upload and organize job site photos by project',

      /* new-estimate form */
      'est.new.title': 'New Estimate',
      'est.new.sub': 'Fill in the job details. BuildOrder will generate a professional, itemized estimate you can send to your client.',
      'est.sec.client': 'Client Information',
      'est.lbl.name': 'Client / Homeowner Name',
      'est.lbl.phone': 'Phone',
      'est.lbl.email': 'Email',
      'est.sec.location': 'Job Location',
      'est.lbl.address': 'Street Address',
      'est.lbl.city': 'City',
      'est.lbl.state': 'State',
      'est.lbl.zip': 'ZIP Code',
      'est.sec.job': 'Job Details',
      'est.lbl.work_type': 'Type of Work',
      'est.lbl.description': 'Project Description',
      'est.lbl.tax': 'Tax Rate %',
      'est.lbl.valid_days': 'Estimate Valid For (days)',
      'est.lbl.notes': 'Additional Notes / Terms',
      'est.sec.items': 'Line Items',
      'est.items.sub': '(optional — AI will generate if left blank)',
      'est.col.desc': 'Description',
      'est.col.qty': 'Qty',
      'est.col.unit': 'Unit',
      'est.col.price': 'Unit Price',
      'est.btn.add': '+ Add Line Item',
      'est.tip': 'Leave line items empty and BuildOrder will generate realistic, itemized pricing from your project description.',
      'est.btn.submit': 'Generate Estimate →',
      'est.btn.note': 'BuildOrder will generate a professional, itemized estimate ready to send to your client.',
      'est.err.name': 'Client name is required.',
      'est.err.desc': 'Project description is required.',

      /* estimate display */
      'est.card.client': 'Client',
      'est.card.details': 'Estimate Details',
      'est.lbl.name2': 'Name',
      'est.lbl.address2': 'Address',
      'est.lbl.work_type2': 'Work Type',
      'est.lbl.tax2': 'Tax Rate',
      'est.lbl.valid2': 'Valid For',
      'est.lbl.created': 'Created',
      'est.lbl.days': ' days',
      'est.btn.regen': 'Regenerate',
      'est.btn.gen': '✶ Generate Estimate',
      'est.generating.h': 'Generating your estimate…',
      'est.no.h': 'No estimate generated yet',
      'est.no.p': 'Click Generate Estimate to create a professional, itemized estimate.',

      /* new-invoice form */
      'inv.new.title': 'New Invoice',
      'inv.new.sub': 'Generate a professional invoice for completed work or a billing milestone.',
      'inv.sec.client': 'Client Information',
      'inv.lbl.name': 'Client Name *',
      'inv.lbl.phone': 'Phone',
      'inv.lbl.email': 'Email',
      'inv.sec.address': 'Service Address',
      'inv.lbl.address': 'Street Address',
      'inv.lbl.city': 'City',
      'inv.lbl.state': 'State',
      'inv.lbl.zip': 'ZIP',
      'inv.lbl.work_type': 'Work Type',
      'inv.sec.items': 'Line Items',
      'inv.col.desc': 'Description',
      'inv.col.qty': 'Qty',
      'inv.col.unit': 'Unit',
      'inv.col.price': 'Unit Price',
      'inv.btn.add': '+ Add Line Item',
      'inv.tot.subtotal': 'Subtotal',
      'inv.tot.tax': 'Tax',
      'inv.tot.total': 'Invoice Total',
      'inv.tot.payments': 'Payments Received',
      'inv.tot.balance': 'Balance Due',
      'inv.sec.terms': 'Invoice Terms',
      'inv.lbl.tax': 'Tax Rate (%)',
      'inv.lbl.due_days': 'Payment Due (days)',
      'inv.lbl.deposit': 'Payments Already Received ($)',
      'inv.lbl.notes': 'Notes (optional)',
      'inv.btn.submit': '★ Generate Invoice',
      'inv.err.name': 'Client name is required.',

      /* invoice display */
      'inv.card.client': 'Client',
      'inv.card.summary': 'Invoice Summary',
      'inv.lbl.name2': 'Name',
      'inv.lbl.phone2': 'Phone',
      'inv.lbl.email2': 'Email',
      'inv.lbl.address2': 'Address',
      'inv.lbl.subtotal': 'Subtotal',
      'inv.lbl.total': 'Invoice Total',
      'inv.lbl.paid': 'Paid',
      'inv.lbl.balance': 'Balance Due',
      'inv.btn.mark_paid': '✓ Mark as Paid',
      'inv.btn.regen': 'Regenerate',
      'inv.btn.gen': '✶ Generate Invoice',
      'inv.generating.h': 'Generating your invoice…',
      'inv.no.h': 'No invoice generated yet',
      'inv.no.p': 'Click Generate Invoice to create a professional invoice ready to send.',

      /* new-change-order form */
      'co.new.title': 'New Change Order',
      'co.new.sub': 'Document a scope change in writing. Both parties must sign before additional work begins.',
      'co.sec.client': 'Client & Job Information',
      'co.lbl.name': 'Client Name *',
      'co.lbl.phone': 'Phone',
      'co.lbl.email': 'Email',
      'co.lbl.address': 'Job Address',
      'co.lbl.city': 'City',
      'co.lbl.state': 'State',
      'co.lbl.work_type': 'Work Type',
      'co.sec.original': 'Original Contract',
      'co.lbl.orig_scope': 'Original Scope of Work',
      'co.lbl.orig_price': 'Original Contract Price ($) *',
      'co.sec.change': 'Change Details',
      'co.lbl.change_desc': 'Description of Change *',
      'co.lbl.reason': 'Reason for Change',
      'co.lbl.change_amt': 'Price Change ($)',
      'co.hint.change_amt': 'Use a negative number to decrease the contract price.',
      'co.lbl.add_days': 'Additional Days to Complete',
      'co.hint.add_days': 'Use 0 for no change, negative to reduce timeline.',
      'co.prev.orig': 'Original Contract',
      'co.prev.change': 'Change Amount',
      'co.prev.new': 'New Contract Total',
      'co.lbl.notes': 'Notes (optional)',
      'co.btn.submit': '★ Generate Change Order',
      'co.err.name': 'Client name is required.',
      'co.err.desc': 'Description of change is required.',
      'co.err.price': 'Original contract price is required.',

      /* change-order display */
      'co.card.client': 'Client',
      'co.card.summary': 'Contract Summary',
      'co.lbl.name2': 'Name',
      'co.lbl.phone2': 'Phone',
      'co.lbl.email2': 'Email',
      'co.lbl.job2': 'Job',
      'co.lbl.orig_price2': 'Original Price',
      'co.lbl.change_amt2': 'Change Amount',
      'co.lbl.extra_days': 'Extra Days',
      'co.lbl.new_total': 'New Total',
      'co.btn.accept': '✓ Mark Accepted',
      'co.btn.regen': 'Regenerate',
      'co.btn.gen': '✶ Generate Change Order',
      'co.generating.h': 'Generating change order…',
      'co.no.h': 'No document generated yet',
      'co.no.p': 'Click Generate Change Order to create a signed-ready change order document.',

      /* new-subcontractor form */
      'sub.new.title': 'New Subcontractor Agreement',
      'sub.new.sub': 'Create a binding agreement with any subcontractor working on your job.',
      'sub.sec.info': 'Subcontractor Information',
      'sub.lbl.name': 'Subcontractor Name *',
      'sub.lbl.company': 'Company Name',
      'sub.lbl.phone': 'Phone',
      'sub.lbl.email': 'Email',
      'sub.lbl.license': 'License Number',
      'sub.lbl.insurance': 'Insurance / GL Policy #',
      'sub.sec.job': 'Job Information',
      'sub.lbl.address': 'Job Address',
      'sub.lbl.city': 'City',
      'sub.lbl.state': 'State',
      'sub.lbl.work_type': 'Work Type',
      'sub.sec.contract': 'Contract Details',
      'sub.lbl.scope': 'Scope of Work *',
      'sub.lbl.amount': 'Contract Amount ($) *',
      'sub.lbl.payment_terms': 'Payment Terms',
      'sub.lbl.start': 'Start Date',
      'sub.lbl.end': 'Estimated Completion',
      'sub.lbl.notes': 'Notes (optional)',
      'sub.btn.submit': '★ Generate Subcontractor Agreement',
      'sub.err.name': 'Subcontractor name is required.',
      'sub.err.scope': 'Scope of work is required.',
      'sub.err.amount': 'Contract amount is required.',

      /* subcontractor display */
      'sub.card.sub': 'Subcontractor',
      'sub.card.contract': 'Contract',
      'sub.lbl.name2': 'Name',
      'sub.lbl.company2': 'Company',
      'sub.lbl.phone2': 'Phone',
      'sub.lbl.license2': 'License',
      'sub.lbl.amount2': 'Amount',
      'sub.lbl.payment2': 'Payment Terms',
      'sub.lbl.start2': 'Start',
      'sub.lbl.end2': 'End',
      'sub.btn.accept': '✓ Mark Accepted',
      'sub.btn.regen': 'Regenerate',
      'sub.btn.gen': '✶ Generate Agreement',
      'sub.generating.h': 'Generating agreement…',
      'sub.no.h': 'No document generated yet',
      'sub.no.p': 'Click Generate Agreement to create a binding subcontractor agreement.',

      /* new-lien-waiver form */
      'lw.new.title': 'New Lien Waiver',
      'lw.sec.type': 'Select Waiver Type',
      'lw.type.cp': 'Conditional Waiver — Progress Payment',
      'lw.type.cp.desc': 'Waiver takes effect when check clears',
      'lw.type.up': 'Unconditional Waiver — Progress Payment',
      'lw.type.up.desc': 'Rights waived immediately upon signing',
      'lw.type.cf': 'Conditional Waiver — Final Payment',
      'lw.type.cf.desc': 'Final conditional on check clearing',
      'lw.type.uf': 'Unconditional Waiver — Final Payment',
      'lw.type.uf.desc': 'All claims released immediately',
      'lw.sec.details': 'Waiver Details',
      'lw.lbl.customer': 'Customer / Owner Name *',
      'lw.lbl.customer_co': 'Customer Company (optional)',
      'lw.lbl.job_address': 'Job Address *',
      'lw.lbl.city': 'City',
      'lw.lbl.state': 'State',
      'lw.lbl.amount': 'Waiver Amount ($) *',
      'lw.lbl.through': 'Through Date *',
      'lw.lbl.payment_date': 'Payment Date (optional)',
      'lw.lbl.check': 'Check # (optional)',
      'lw.sec.claimant': 'Claimant (Your Info)',
      'lw.lbl.cl_name': 'Your Name *',
      'lw.lbl.cl_company': 'Your Company',
      'lw.btn.submit': '★ Generate Lien Waiver',
      'lw.err.type': 'Please select a waiver type.',
      'lw.err.customer': 'Customer name is required.',
      'lw.err.address': 'Job address is required.',
      'lw.err.amount': 'Waiver amount is required.',
      'lw.err.through': 'Through date is required.',
      'lw.err.claimant': 'Your name is required.',

      /* lien-waiver display */
      'lw.card.details': 'Waiver Details',
      'lw.card.parties': 'Parties',
      'lw.lbl.amount2': 'Amount',
      'lw.lbl.through2': 'Through Date',
      'lw.lbl.payment2': 'Payment Date',
      'lw.lbl.check2': 'Check #',
      'lw.lbl.claimant2': 'Claimant',
      'lw.lbl.customer2': 'Customer',
      'lw.lbl.property': 'Property',
      'lw.btn.regen': 'Regenerate',
      'lw.btn.gen': '✶ Generate Lien Waiver',
      'lw.generating.h': 'Generating lien waiver…',
      'lw.no.h': 'No document generated yet',
      'lw.no.p': 'Click Generate Lien Waiver to create the document.',

      /* new-takeoff form */
      'to.new.title': 'New Material Takeoff',
      'to.new.sub': 'Enter your project dimensions and BuildOrder will generate a complete materials list.',
      'to.lbl.type': 'Project Type *',
      'to.lbl.description': 'Project Description *',
      'to.sec.dims': 'Dimensions',
      'to.lbl.sqft': 'Total Square Footage',
      'to.lbl.linear': 'Linear Footage',
      'to.lbl.length': 'Length (ft)',
      'to.lbl.width': 'Width (ft)',
      'to.lbl.height': 'Height (ft)',
      'to.lbl.rooms': 'Number of Rooms',
      'to.lbl.perimeter': 'Perimeter (ft)',
      'to.lbl.custom': 'Custom Dimension',
      'to.lbl.waste': 'Waste Factor (%)',
      'to.lbl.notes': 'Notes (optional)',
      'to.lbl.address': 'Job Address (optional)',
      'to.btn.submit': '★ Generate Material Takeoff',
      'to.err.type': 'Project type is required.',
      'to.err.desc': 'Project description is required.',
      'to.err.dims': 'At least one dimension is required.',

      /* takeoff display */
      'to.card.project': 'Project',
      'to.card.dims': 'Dimensions',
      'to.lbl.type2': 'Type',
      'to.lbl.location': 'Location',
      'to.lbl.created': 'Created',
      'to.lbl.measurements': 'Measurements',
      'to.lbl.waste2': 'Waste Factor',
      'to.lbl.rooms2': 'Rooms',
      'to.btn.recalc': 'Recalculate',
      'to.btn.gen': '✶ Generate Takeoff',
      'to.generating.h': 'Calculating materials…',
      'to.generating.p': 'BuildOrder is generating your complete material takeoff. About 15 seconds.',
      'to.no.h': 'No takeoff generated yet',
      'to.no.p': 'Click Generate Takeoff to get a complete materials list with quantities and cost estimates.',

      /* photos */
      'ph.title': 'Job Photo Log',
      'ph.upload': 'Upload Photos',
      'ph.filter': 'Filter by job',
      'ph.all_jobs': 'All Jobs',
      'ph.drag': 'Drag & drop photos here or click to browse',
      'ph.modal.title': 'Add Photo Details',
      'ph.lbl.caption': 'Caption (optional)',
      'ph.lbl.job': 'Assign to Job',
      'ph.lbl.no_job': 'No job assigned',
      'ph.btn.upload': 'Upload',
      'ph.btn.cancel': 'Cancel',
      'ph.no.h': 'No photos yet',
      'ph.no.p': 'Upload your first job site photo to get started.',

      /* generic generating / error */
      'gen.generating': 'Generating…',
      'gen.calculating': 'Calculating…',
      'gen.network_err': 'Network error — please try again.',
      'gen.failed': 'Generation failed.',
      'btn.signout': 'Sign Out',
    },

    es: {
      /* nav */
      'nav.back': '← Panel',

      /* common buttons */
      'btn.copy': 'Copiar',
      'btn.download': 'Descargar .txt',
      'btn.try_again': 'Intentar de nuevo',
      'btn.saving': 'Guardando…',

      /* status */
      'status.draft': 'borrador',
      'status.sent': 'enviado',
      'status.paid': 'pagado',
      'status.signed': 'firmado',
      'status.complete': 'completo',
      'status.accepted': 'aceptado',

      /* dashboard */
      'dash.tools': 'Herramientas',
      'dash.recent': 'Documentos Recientes',
      'dash.filter.all': 'Todos',
      'dash.filter.contracts': 'Contratos',
      'dash.filter.estimates': 'Presupuestos',
      'dash.filter.invoices': 'Facturas',
      'dash.filter.change_orders': 'Órdenes de Cambio',
      'dash.filter.subcontractors': 'Subcontratistas',
      'dash.filter.lien_waivers': 'Renuncia de Gravamen',
      'dash.filter.takeoffs': 'Lista de Materiales',
      'dash.stat.total': 'Total Docs',
      'dash.stat.contracts': 'Contratos',
      'dash.stat.invoices': 'Facturas',
      'dash.stat.outstanding': 'Pendiente',
      'dash.empty': 'Sin documentos aún',
      'dash.empty.sub': 'Selecciona una herramienta arriba para crear tu primer documento.',
      'dash.new': 'Nuevo',

      /* tool names */
      'tool.contract': 'Generador de Contratos',
      'tool.contract.desc': 'Contratos residenciales y comerciales por estado',
      'tool.estimate': 'Generador de Presupuestos',
      'tool.estimate.desc': 'Presupuestos profesionales con partidas detalladas',
      'tool.invoice': 'Generador de Facturas',
      'tool.invoice.desc': 'Facturas listas para cobro con partidas',
      'tool.change_order': 'Orden de Cambio',
      'tool.change_order.desc': 'Documenta cambios de alcance y ajustes de precio',
      'tool.subcontractor': 'Contrato de Subcontratista',
      'tool.subcontractor.desc': 'Contratos completos con requisitos de seguro',
      'tool.lien_waiver': 'Renuncia de Gravamen',
      'tool.lien_waiver.desc': '4 tipos de renuncias — condicionales e incondicionales',
      'tool.takeoff': 'Lista de Materiales',
      'tool.takeoff.desc': 'Lista de materiales con cantidades y costos estimados',
      'tool.photos': 'Registro de Fotos',
      'tool.photos.desc': 'Sube y organiza fotos del sitio de trabajo',

      /* new-estimate form */
      'est.new.title': 'Nuevo Presupuesto',
      'est.new.sub': 'Completa los detalles del trabajo. BuildOrder generará un presupuesto profesional y detallado para tu cliente.',
      'est.sec.client': 'Información del Cliente',
      'est.lbl.name': 'Nombre del Cliente / Propietario',
      'est.lbl.phone': 'Teléfono',
      'est.lbl.email': 'Correo',
      'est.sec.location': 'Ubicación del Trabajo',
      'est.lbl.address': 'Dirección',
      'est.lbl.city': 'Ciudad',
      'est.lbl.state': 'Estado',
      'est.lbl.zip': 'Código Postal',
      'est.sec.job': 'Detalles del Trabajo',
      'est.lbl.work_type': 'Tipo de Trabajo',
      'est.lbl.description': 'Descripción del Proyecto',
      'est.lbl.tax': 'Tasa de Impuesto %',
      'est.lbl.valid_days': 'Presupuesto Válido Por (días)',
      'est.lbl.notes': 'Notas Adicionales / Términos',
      'est.sec.items': 'Partidas',
      'est.items.sub': '(opcional — la IA generará si se deja en blanco)',
      'est.col.desc': 'Descripción',
      'est.col.qty': 'Cant.',
      'est.col.unit': 'Unidad',
      'est.col.price': 'Precio Unit.',
      'est.btn.add': '+ Agregar Partida',
      'est.tip': 'Deja las partidas vacías y BuildOrder generará precios realistas basados en tu descripción.',
      'est.btn.submit': 'Generar Presupuesto →',
      'est.btn.note': 'BuildOrder generará un presupuesto profesional listo para enviar a tu cliente.',
      'est.err.name': 'El nombre del cliente es requerido.',
      'est.err.desc': 'La descripción del proyecto es requerida.',

      /* estimate display */
      'est.card.client': 'Cliente',
      'est.card.details': 'Detalles del Presupuesto',
      'est.lbl.name2': 'Nombre',
      'est.lbl.address2': 'Dirección',
      'est.lbl.work_type2': 'Tipo de Trabajo',
      'est.lbl.tax2': 'Impuesto',
      'est.lbl.valid2': 'Válido Por',
      'est.lbl.created': 'Creado',
      'est.lbl.days': ' días',
      'est.btn.regen': 'Regenerar',
      'est.btn.gen': '✶ Generar Presupuesto',
      'est.generating.h': 'Generando tu presupuesto…',
      'est.no.h': 'Aún no se ha generado el presupuesto',
      'est.no.p': 'Haz clic en Generar Presupuesto para crear un presupuesto profesional.',

      /* new-invoice form */
      'inv.new.title': 'Nueva Factura',
      'inv.new.sub': 'Genera una factura profesional para trabajo completado o un hito de pago.',
      'inv.sec.client': 'Información del Cliente',
      'inv.lbl.name': 'Nombre del Cliente *',
      'inv.lbl.phone': 'Teléfono',
      'inv.lbl.email': 'Correo',
      'inv.sec.address': 'Dirección del Servicio',
      'inv.lbl.address': 'Dirección',
      'inv.lbl.city': 'Ciudad',
      'inv.lbl.state': 'Estado',
      'inv.lbl.zip': 'Código Postal',
      'inv.lbl.work_type': 'Tipo de Trabajo',
      'inv.sec.items': 'Partidas',
      'inv.col.desc': 'Descripción',
      'inv.col.qty': 'Cant.',
      'inv.col.unit': 'Unidad',
      'inv.col.price': 'Precio Unit.',
      'inv.btn.add': '+ Agregar Partida',
      'inv.tot.subtotal': 'Subtotal',
      'inv.tot.tax': 'Impuesto',
      'inv.tot.total': 'Total de Factura',
      'inv.tot.payments': 'Pagos Recibidos',
      'inv.tot.balance': 'Saldo Pendiente',
      'inv.sec.terms': 'Términos de Factura',
      'inv.lbl.tax': 'Tasa de Impuesto (%)',
      'inv.lbl.due_days': 'Vencimiento en (días)',
      'inv.lbl.deposit': 'Pagos Ya Recibidos ($)',
      'inv.lbl.notes': 'Notas (opcional)',
      'inv.btn.submit': '★ Generar Factura',
      'inv.err.name': 'El nombre del cliente es requerido.',

      /* invoice display */
      'inv.card.client': 'Cliente',
      'inv.card.summary': 'Resumen de Factura',
      'inv.lbl.name2': 'Nombre',
      'inv.lbl.phone2': 'Teléfono',
      'inv.lbl.email2': 'Correo',
      'inv.lbl.address2': 'Dirección',
      'inv.lbl.subtotal': 'Subtotal',
      'inv.lbl.total': 'Total de Factura',
      'inv.lbl.paid': 'Pagado',
      'inv.lbl.balance': 'Saldo Pendiente',
      'inv.btn.mark_paid': '✓ Marcar como Pagado',
      'inv.btn.regen': 'Regenerar',
      'inv.btn.gen': '✶ Generar Factura',
      'inv.generating.h': 'Generando tu factura…',
      'inv.no.h': 'Aún no se ha generado la factura',
      'inv.no.p': 'Haz clic en Generar Factura para crear una factura profesional.',

      /* new-change-order form */
      'co.new.title': 'Nueva Orden de Cambio',
      'co.new.sub': 'Documenta un cambio de alcance por escrito. Ambas partes deben firmar antes de iniciar el trabajo adicional.',
      'co.sec.client': 'Información del Cliente y Trabajo',
      'co.lbl.name': 'Nombre del Cliente *',
      'co.lbl.phone': 'Teléfono',
      'co.lbl.email': 'Correo',
      'co.lbl.address': 'Dirección del Trabajo',
      'co.lbl.city': 'Ciudad',
      'co.lbl.state': 'Estado',
      'co.lbl.work_type': 'Tipo de Trabajo',
      'co.sec.original': 'Contrato Original',
      'co.lbl.orig_scope': 'Alcance Original del Trabajo',
      'co.lbl.orig_price': 'Precio Original del Contrato ($) *',
      'co.sec.change': 'Detalles del Cambio',
      'co.lbl.change_desc': 'Descripción del Cambio *',
      'co.lbl.reason': 'Razón del Cambio',
      'co.lbl.change_amt': 'Cambio de Precio ($)',
      'co.hint.change_amt': 'Usa un número negativo para reducir el precio del contrato.',
      'co.lbl.add_days': 'Días Adicionales para Completar',
      'co.hint.add_days': 'Usa 0 para sin cambio, negativo para reducir el plazo.',
      'co.prev.orig': 'Contrato Original',
      'co.prev.change': 'Monto del Cambio',
      'co.prev.new': 'Nuevo Total del Contrato',
      'co.lbl.notes': 'Notas (opcional)',
      'co.btn.submit': '★ Generar Orden de Cambio',
      'co.err.name': 'El nombre del cliente es requerido.',
      'co.err.desc': 'La descripción del cambio es requerida.',
      'co.err.price': 'El precio original del contrato es requerido.',

      /* change-order display */
      'co.card.client': 'Cliente',
      'co.card.summary': 'Resumen del Contrato',
      'co.lbl.name2': 'Nombre',
      'co.lbl.phone2': 'Teléfono',
      'co.lbl.email2': 'Correo',
      'co.lbl.job2': 'Trabajo',
      'co.lbl.orig_price2': 'Precio Original',
      'co.lbl.change_amt2': 'Monto del Cambio',
      'co.lbl.extra_days': 'Días Extra',
      'co.lbl.new_total': 'Nuevo Total',
      'co.btn.accept': '✓ Marcar como Aceptado',
      'co.btn.regen': 'Regenerar',
      'co.btn.gen': '✶ Generar Orden de Cambio',
      'co.generating.h': 'Generando orden de cambio…',
      'co.no.h': 'Aún no se ha generado el documento',
      'co.no.p': 'Haz clic en Generar Orden de Cambio para crear el documento.',

      /* new-subcontractor form */
      'sub.new.title': 'Nuevo Contrato de Subcontratista',
      'sub.new.sub': 'Crea un acuerdo vinculante con cualquier subcontratista que trabaje en tu proyecto.',
      'sub.sec.info': 'Información del Subcontratista',
      'sub.lbl.name': 'Nombre del Subcontratista *',
      'sub.lbl.company': 'Nombre de la Empresa',
      'sub.lbl.phone': 'Teléfono',
      'sub.lbl.email': 'Correo',
      'sub.lbl.license': 'Número de Licencia',
      'sub.lbl.insurance': 'Seguro / Póliza GL #',
      'sub.sec.job': 'Información del Trabajo',
      'sub.lbl.address': 'Dirección del Trabajo',
      'sub.lbl.city': 'Ciudad',
      'sub.lbl.state': 'Estado',
      'sub.lbl.work_type': 'Tipo de Trabajo',
      'sub.sec.contract': 'Detalles del Contrato',
      'sub.lbl.scope': 'Alcance del Trabajo *',
      'sub.lbl.amount': 'Monto del Contrato ($) *',
      'sub.lbl.payment_terms': 'Términos de Pago',
      'sub.lbl.start': 'Fecha de Inicio',
      'sub.lbl.end': 'Terminación Estimada',
      'sub.lbl.notes': 'Notas (opcional)',
      'sub.btn.submit': '★ Generar Contrato de Subcontratista',
      'sub.err.name': 'El nombre del subcontratista es requerido.',
      'sub.err.scope': 'El alcance del trabajo es requerido.',
      'sub.err.amount': 'El monto del contrato es requerido.',

      /* subcontractor display */
      'sub.card.sub': 'Subcontratista',
      'sub.card.contract': 'Contrato',
      'sub.lbl.name2': 'Nombre',
      'sub.lbl.company2': 'Empresa',
      'sub.lbl.phone2': 'Teléfono',
      'sub.lbl.license2': 'Licencia',
      'sub.lbl.amount2': 'Monto',
      'sub.lbl.payment2': 'Términos de Pago',
      'sub.lbl.start2': 'Inicio',
      'sub.lbl.end2': 'Fin',
      'sub.btn.accept': '✓ Marcar como Aceptado',
      'sub.btn.regen': 'Regenerar',
      'sub.btn.gen': '✶ Generar Contrato',
      'sub.generating.h': 'Generando contrato…',
      'sub.no.h': 'Aún no se ha generado el documento',
      'sub.no.p': 'Haz clic en Generar Contrato para crear el acuerdo de subcontratista.',

      /* new-lien-waiver form */
      'lw.new.title': 'Nueva Renuncia de Gravamen',
      'lw.sec.type': 'Selecciona el Tipo de Renuncia',
      'lw.type.cp': 'Renuncia Condicional — Pago Parcial',
      'lw.type.cp.desc': 'La renuncia toma efecto cuando el cheque se cobra',
      'lw.type.up': 'Renuncia Incondicional — Pago Parcial',
      'lw.type.up.desc': 'Los derechos se renuncian inmediatamente al firmar',
      'lw.type.cf': 'Renuncia Condicional — Pago Final',
      'lw.type.cf.desc': 'Final condicional al cobro del cheque',
      'lw.type.uf': 'Renuncia Incondicional — Pago Final',
      'lw.type.uf.desc': 'Todos los reclamos se liberan inmediatamente',
      'lw.sec.details': 'Detalles de la Renuncia',
      'lw.lbl.customer': 'Nombre del Cliente / Propietario *',
      'lw.lbl.customer_co': 'Empresa del Cliente (opcional)',
      'lw.lbl.job_address': 'Dirección del Trabajo *',
      'lw.lbl.city': 'Ciudad',
      'lw.lbl.state': 'Estado',
      'lw.lbl.amount': 'Monto de la Renuncia ($) *',
      'lw.lbl.through': 'Fecha Hasta *',
      'lw.lbl.payment_date': 'Fecha de Pago (opcional)',
      'lw.lbl.check': 'Cheque # (opcional)',
      'lw.sec.claimant': 'Reclamante (Tu Información)',
      'lw.lbl.cl_name': 'Tu Nombre *',
      'lw.lbl.cl_company': 'Tu Empresa',
      'lw.btn.submit': '★ Generar Renuncia de Gravamen',
      'lw.err.type': 'Por favor selecciona un tipo de renuncia.',
      'lw.err.customer': 'El nombre del cliente es requerido.',
      'lw.err.address': 'La dirección del trabajo es requerida.',
      'lw.err.amount': 'El monto de la renuncia es requerido.',
      'lw.err.through': 'La fecha hasta es requerida.',
      'lw.err.claimant': 'Tu nombre es requerido.',

      /* lien-waiver display */
      'lw.card.details': 'Detalles de la Renuncia',
      'lw.card.parties': 'Partes',
      'lw.lbl.amount2': 'Monto',
      'lw.lbl.through2': 'Fecha Hasta',
      'lw.lbl.payment2': 'Fecha de Pago',
      'lw.lbl.check2': 'Cheque #',
      'lw.lbl.claimant2': 'Reclamante',
      'lw.lbl.customer2': 'Cliente',
      'lw.lbl.property': 'Propiedad',
      'lw.btn.regen': 'Regenerar',
      'lw.btn.gen': '✶ Generar Renuncia de Gravamen',
      'lw.generating.h': 'Generando renuncia de gravamen…',
      'lw.no.h': 'Aún no se ha generado el documento',
      'lw.no.p': 'Haz clic en Generar para crear el documento.',

      /* new-takeoff form */
      'to.new.title': 'Nueva Lista de Materiales',
      'to.new.sub': 'Ingresa las dimensiones de tu proyecto y BuildOrder generará una lista completa de materiales.',
      'to.lbl.type': 'Tipo de Proyecto *',
      'to.lbl.description': 'Descripción del Proyecto *',
      'to.sec.dims': 'Dimensiones',
      'to.lbl.sqft': 'Pies Cuadrados Totales',
      'to.lbl.linear': 'Pies Lineales',
      'to.lbl.length': 'Largo (pies)',
      'to.lbl.width': 'Ancho (pies)',
      'to.lbl.height': 'Alto (pies)',
      'to.lbl.rooms': 'Número de Cuartos',
      'to.lbl.perimeter': 'Perímetro (pies)',
      'to.lbl.custom': 'Dimensión Personalizada',
      'to.lbl.waste': 'Factor de Desperdicio (%)',
      'to.lbl.notes': 'Notas (opcional)',
      'to.lbl.address': 'Dirección del Trabajo (opcional)',
      'to.btn.submit': '★ Generar Lista de Materiales',
      'to.err.type': 'El tipo de proyecto es requerido.',
      'to.err.desc': 'La descripción del proyecto es requerida.',
      'to.err.dims': 'Se requiere al menos una dimensión.',

      /* takeoff display */
      'to.card.project': 'Proyecto',
      'to.card.dims': 'Dimensiones',
      'to.lbl.type2': 'Tipo',
      'to.lbl.location': 'Ubicación',
      'to.lbl.created': 'Creado',
      'to.lbl.measurements': 'Medidas',
      'to.lbl.waste2': 'Factor de Desperdicio',
      'to.lbl.rooms2': 'Cuartos',
      'to.btn.recalc': 'Recalcular',
      'to.btn.gen': '✶ Generar Lista de Materiales',
      'to.generating.h': 'Calculando materiales…',
      'to.generating.p': 'BuildOrder está generando tu lista de materiales. Aproximadamente 15 segundos.',
      'to.no.h': 'Aún no se ha generado la lista',
      'to.no.p': 'Haz clic en Generar para obtener una lista completa de materiales con cantidades y costos.',

      /* photos */
      'ph.title': 'Registro de Fotos',
      'ph.upload': 'Subir Fotos',
      'ph.filter': 'Filtrar por trabajo',
      'ph.all_jobs': 'Todos los Trabajos',
      'ph.drag': 'Arrastra fotos aquí o haz clic para buscar',
      'ph.modal.title': 'Agregar Detalles de Foto',
      'ph.lbl.caption': 'Descripción (opcional)',
      'ph.lbl.job': 'Asignar al Trabajo',
      'ph.lbl.no_job': 'Sin trabajo asignado',
      'ph.btn.upload': 'Subir',
      'ph.btn.cancel': 'Cancelar',
      'ph.no.h': 'Sin fotos aún',
      'ph.no.p': 'Sube tu primera foto del sitio de trabajo para comenzar.',

      /* generic */
      'gen.generating': 'Generando…',
      'gen.calculating': 'Calculando…',
      'gen.network_err': 'Error de red — por favor intenta de nuevo.',
      'gen.failed': 'Error en la generación.',
      'btn.signout': 'Cerrar Sesión',
    }
  };

  window.getLang = function () {
    return localStorage.getItem('bo-lang') || 'en';
  };

  window.setLang = function (l) {
    localStorage.setItem('bo-lang', l);
    location.reload();
  };

  window.T = function (key) {
    var l = getLang();
    return (TR[l] && TR[l][key] !== undefined ? TR[l][key] : (TR.en[key] !== undefined ? TR.en[key] : key));
  };

  window.applyI18n = function () {
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      el.textContent = T(el.getAttribute('data-i18n'));
    });
    document.querySelectorAll('[data-i18n-html]').forEach(function (el) {
      el.innerHTML = T(el.getAttribute('data-i18n-html'));
    });
    document.querySelectorAll('[data-i18n-ph]').forEach(function (el) {
      el.placeholder = T(el.getAttribute('data-i18n-ph'));
    });
  };

  document.addEventListener('DOMContentLoaded', function () {
    /* activate toggle button */
    var btn = document.getElementById('lang-btn-' + getLang());
    if (btn) btn.classList.add('active');
    /* translate static elements */
    applyI18n();
  });
})();
